# Generated by Django 3.0.6 on 2020-09-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ONGOING', 'On going'), ('PLAYED', 'Played'), ('NOT_STARTED', 'Not Started'), ('ABORTED', 'Aborted')], default='NOT_STARTED', max_length=100)),
                ('result', jsonfield.fields.JSONField(default={'winner': 0, 'winner_total_sixes': 0, 'winner_total_wickets': 0, 'winning_team_score': 0})),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filed_to_refer', models.CharField(choices=[('winner', 'Match Winner'), ('winning_team_score', 'Winning Team Score'), ('winner_total_sixes', 'Winner Total Sixes'), ('winner_total_wickets', 'Winning Team Wickets')], max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.IntegerField(choices=[(0, 'Match'), (1, 'League')], default=0)),
                ('rule', models.IntegerField(choices=[(0, 'Exact Match'), (1, 'Range')], default=0)),
                ('guess_range', models.IntegerField(default=0)),
                ('point_weight', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_to', models.IntegerField(choices=[(0, 'Number'), (1, 'Team')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(default='IPL', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', jsonfield.fields.JSONField(default={'winner': 'Match Winner', 'winner_total_sixes': 'Winner Total Sixes', 'winner_total_wickets': 'Winning Team Wickets', 'winning_team_score': 'Winning Team Score'})),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_score', to='accounts.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team1', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team2', to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='accounts.Team'),
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll', to='accounts.Department')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team1', 'team2')},
        ),
    ]
